:setvar scriptsPath C:\Users\aramos\Documents\clients\gos\prodload\package-gos-archibus-update-v5\03-package-gos-archibus-phase2\01-SQL\
:r $(scriptsPath)01-afm_ptasks.sql
:r $(scriptsPath)02-eq_id_field_length.sql
:r $(scriptsPath)03-eq-ddl.sql
:r $(scriptsPath)04-eq-dml.sql
:r $(scriptsPath)05-it-ddl.sql
:r $(scriptsPath)06-it-dml.sql
:r $(scriptsPath)07-vn-ddl.sql
:r $(scriptsPath)08-vn-dml.sql
:r $(scriptsPath)09-pv-ddl.sql
:r $(scriptsPath)10-pv-dml.sql
:r $(scriptsPath)11-pt-ddl.sql
:r $(scriptsPath)12-pt-dml.sql
:r $(scriptsPath)13-wo-ddl.sql
:r $(scriptsPath)14-wo.dml.sql
:r $(scriptsPath)15-tl-ddl.sql
:r $(scriptsPath)16-tl-dml.sql
:r $(scriptsPath)17-midas_org-ddl.sql
:r $(scriptsPath)18-midas_org-dml.sql
:r $(scriptsPath)19-workgrp-ddl.sql
:r $(scriptsPath)20-workgrp-dml.sql
:r $(scriptsPath)21-wr-ddl.sql
:r $(scriptsPath)22-wr-dml.sql
:r $(scriptsPath)23-pmp-ddl.sql
:r $(scriptsPath)24-pmp-dml.sql
:r $(scriptsPath)25-wr_other-ddl.sql
:r $(scriptsPath)26-wr_other-dml.sql
:r $(scriptsPath)27-hwo-ddl.sql
:r $(scriptsPath)28-hwo.dml.sql
:r $(scriptsPath)29-hwr-ddl.sql
:r $(scriptsPath)30-hwr-dml.sql
:r $(scriptsPath)31-hwr_other-ddl.sql
:r $(scriptsPath)32-hwr_other-dml.sql
:r $(scriptsPath)33-wohwo-ddl.sql
:r $(scriptsPath)34-wohwo-dml.sql
:r $(scriptsPath)35-wrhwr-ddl.sql
:r $(scriptsPath)36-wrhwr-dml.sql
:r $(scriptsPath)37-wrview-dml.sql
:r $(scriptsPath)38-hactivity_logmonth-dml.sql
:r $(scriptsPath)39-activity_log_hactivity_log-dml.sql
:r $(scriptsPath)40-activity_logview-dml.sql
:r $(scriptsPath)41-hwr_month-dml.sql
:r $(scriptsPath)42-activity_log-ddl.sql
:r $(scriptsPath)43-activity_log-dml.sql
:r $(scriptsPath)44-afm_groups.sql
:r $(scriptsPath)45-afm_roles.sql
:r $(scriptsPath)46-afm_groupsforroles.sql
:r $(scriptsPath)47-afm_roleprocs.sql
:r $(scriptsPath)48-afm_ptasks.sql
:r $(scriptsPath)49-afm_activity_params.sql
:r $(scriptsPath)50-helpdesk_roles.sql
:r $(scriptsPath)51-vn_ac.sql
:r $(scriptsPath)52-messages.sql
:r $(scriptsPath)53-afm_usrs-ddl.sql
:r $(scriptsPath)54-afm_usrs-dml.sql
:r $(scriptsPath)55-contact.sql
:r $(scriptsPath)56-midas_org_fix.sql